# Generated by Django 4.2.5 on 2024-04-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('city', models.CharField(max_length=50, verbose_name='所在城市')),
                ('addr', models.CharField(max_length=200, verbose_name='具体地址')),
                ('detail', models.TextField(verbose_name='酒店描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('stock', models.IntegerField(verbose_name='剩余房间数')),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='产品名称')),
                ('detail', models.TextField(verbose_name='产品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('type', models.CharField(max_length=100, verbose_name='类型')),
                ('sales', models.PositiveIntegerField(max_length=20, verbose_name='销量')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='景点名称')),
                ('description', models.TextField(default=None, verbose_name='景点描述')),
                ('city', models.CharField(default=None, max_length=50, verbose_name='所在城市')),
                ('location', models.CharField(default=None, max_length=200, verbose_name='具体地址')),
                ('open_hours', models.CharField(default=None, max_length=100, verbose_name='开放时间')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=None, max_digits=8, verbose_name='门票价格')),
                ('star', models.IntegerField(default=None, verbose_name='景点级别')),
                ('stock', models.IntegerField(default=None, verbose_name='余票')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='景点标题')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default=123123, max_length=20, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号码')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='ScenicSpotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('ScenicSpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scenicspot', verbose_name='景区')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '景区订单',
                'verbose_name_plural': '景区订单',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '产品订单',
                'verbose_name_plural': '产品订单',
            },
        ),
        migrations.CreateModel(
            name='HotelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='酒店')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '酒店订单',
                'verbose_name_plural': '酒店订单',
            },
        ),
    ]
