# Generated by Django 4.2.5 on 2024-04-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_hotelorder_status_alter_productorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelorder',
            name='status',
            field=models.CharField(default='已取消', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(default='已取消', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='scenicspotorder',
            name='status',
            field=models.CharField(default='已取消', max_length=10, verbose_name='状态'),
        ),
    ]
