# Generated by Django 4.2.5 on 2024-04-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '游客', 'verbose_name_plural': '游客'},
        ),
        migrations.RemoveField(
            model_name='scenicspot',
            name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='游客名称'),
        ),
    ]
